const c=document.getElementById('game'),x=c.getContext('2d');let W,H,D=1;function resize(){D=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;c.width=W*D;c.height=H*D;c.style.width=W+'px';c.style.height=H+'px';x.setTransform(D,0,0,D,0,0)}addEventListener('resize',resize);resize();
const keys={};onkeydown=e=>{keys[e.key.toLowerCase()]=1;if(e.key.toLowerCase()==='r')reset()};onkeyup=e=>keys[e.key.toLowerCase()]=0;document.querySelectorAll('#touch button').forEach(b=>{let k=b.dataset.k;b.onpointerdown=e=>{e.preventDefault();keys[k]=1};b.onpointerup=b.onpointercancel=()=>keys[k]=0});
let boat,wake=[];function reset(){boat={x:0,y:100,a:-.3,v:0,rock:0}}reset();
const island={x:440,y:-80,r:255};const rocks=[[-370,-220,42],[-280,310,28],[760,260,48],[690,-420,30]];
function water(t,camx,camy){x.fillStyle='#173d43';x.fillRect(0,0,W,H);x.lineWidth=1;for(let j=-80;j<H+80;j+=32)for(let i=-100;i<W+100;i+=72){let wx=i+((camx*.12)%72),wy=j+((camy*.08)%32),q=Math.sin(t*.001+i*.03+j*.02)*7;x.strokeStyle='rgba(144,190,187,.13)';x.beginPath();x.moveTo(wx-24,wy+q);x.quadraticCurveTo(wx,wy+q-5,wx+28,wy+q);x.stroke()}}
function worldToScreen(px,py,camx,camy){return [W/2+(px-camx),H/2+(py-camy)*.62]}
function drawIsland(camx,camy){let [sx,sy]=worldToScreen(island.x,island.y,camx,camy);x.save();x.translate(sx,sy);x.scale(1,.62);x.fillStyle='#a69868';x.beginPath();x.ellipse(0,0,island.r+28,island.r+22,0,0,Math.PI*2);x.fill();x.fillStyle='#334934';x.beginPath();x.ellipse(0,-8,island.r,island.r*.92,0,0,Math.PI*2);x.fill();x.fillStyle='#24392d';for(let i=0;i<18;i++){let a=i*2.4,r=45+(i*31)%170,px=Math.cos(a)*r,py=Math.sin(a)*r*.8;x.beginPath();x.arc(px,py,18+(i%4)*4,0,7);x.fill()}x.fillStyle='#756044';x.fillRect(-65,185,130,24);x.fillRect(-15,185,30,115);x.restore()}
function drawRocks(camx,camy){for(const r of rocks){let [sx,sy]=worldToScreen(r[0],r[1],camx,camy);x.fillStyle='#56605b';x.beginPath();x.ellipse(sx,sy,r[2],r[2]*.55,-.2,0,7);x.fill()}}
function drawWake(camx,camy){for(let i=0;i<wake.length;i++){let w=wake[i],[sx,sy]=worldToScreen(w.x,w.y,camx,camy);x.strokeStyle=`rgba(205,225,214,${w.life*.3})`;x.lineWidth=2;x.beginPath();x.ellipse(sx,sy,10+(1-w.life)*28,(5+(1-w.life)*12)*.62,0,0,7);x.stroke()}}
function drawBoat(){x.save();x.translate(W/2,H/2);x.rotate(boat.a);x.translate(0,Math.sin(boat.rock)*2);x.fillStyle='rgba(0,0,0,.28)';x.beginPath();x.ellipse(4,8,34,13,0,0,7);x.fill();x.fillStyle='#6f5137';x.strokeStyle='#261e18';x.lineWidth=3;x.beginPath();x.moveTo(34,0);x.quadraticCurveTo(18,-17,-28,-13);x.lineTo(-37,0);x.lineTo(-28,13);x.quadraticCurveTo(18,17,34,0);x.fill();x.stroke();x.fillStyle='#d8c7a0';x.fillRect(-7,-9,17,18);x.strokeRect(-7,-9,17,18);x.fillStyle='#272a27';x.fillRect(-34,-7,9,14);x.fillStyle='rgba(60,55,48,.38)';for(let i=0;i<3;i++){x.beginPath();x.arc(-43-i*7,-8-i*4,5+i*2,0,7);x.fill()}x.restore()}
function collision(nx,ny){let dx=nx-island.x,dy=ny-island.y;if(Math.hypot(dx,dy)<island.r+18)return true;return rocks.some(r=>Math.hypot(nx-r[0],ny-r[1])<r[2]+15)}
let last=performance.now();function loop(t){let dt=Math.min((t-last)/1000,.033);last=t;let throttle=(keys.w||keys.arrowup?1:0)-(keys.s||keys.arrowdown?1:0),turn=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0);boat.v+=throttle*70*dt;boat.v*=Math.pow(.985,dt*60);boat.v=Math.max(-32,Math.min(120,boat.v));if(keys[' '])boat.v*=Math.pow(.91,dt*60);boat.a+=turn*(.75+Math.min(Math.abs(boat.v)/100,.6))*dt*(boat.v>=0?1:-1);let nx=boat.x+Math.cos(boat.a)*boat.v*dt,ny=boat.y+Math.sin(boat.a)*boat.v*dt;if(!collision(nx,ny)){boat.x=nx;boat.y=ny}else boat.v*=-.15;boat.rock+=dt*(2.4+Math.abs(boat.v)*.015);if(Math.abs(boat.v)>12&&Math.random()<dt*10)wake.push({x:boat.x-Math.cos(boat.a)*32,y:boat.y-Math.sin(boat.a)*32,life:1});wake.forEach(w=>w.life-=dt*.55);wake=wake.filter(w=>w.life>0);let camx=boat.x-Math.cos(boat.a)*80,camy=boat.y-Math.sin(boat.a)*80;water(t,camx,camy);drawIsland(camx,camy);drawRocks(camx,camy);drawWake(camx,camy);drawBoat();document.getElementById('speed').textContent=(Math.abs(boat.v)*.075).toFixed(1)+' kn';let dist=Math.hypot(boat.x-island.x,boat.y-island.y)-island.r;document.getElementById('depth').textContent='Depth '+Math.max(3,Math.min(18,Math.round(dist/30+3)))+' ft';requestAnimationFrame(loop)}requestAnimationFrame(loop);